version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint_client:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cd client && yarn lint
          name: Lint client code

  lint_api:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cd api && yarn lint
          name: Lint API code

  build_and_test_client: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cd client && yarn test
          name: Run client tests
      - run:
          command: cd client && yarn build
          name: Build frontend

  build_and_test_api:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cd api && yarn test
          name: Run backend tests

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
            apt-get update && \
            apt-get install -y rsync openssh-client docker-compose yarn
      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run:
          name: Add to Known Hosts
          command: |
            ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
      - run:
          name: Copy Source
          command: |
            rsync -avz --delete \
              --exclude='.*' \
              --exclude='*docs*' \
              --exclude='*node_modules*' \
              --exclude='*.md' \
              --exclude='*eslint*' \
              --exclude='*.test.*' \
              --exclude='*spec*' \
              --exclude='build/' \
              --exclude='dist/' \
              --exclude='*.log' \
              --exclude='tmp/' \
              --exclude='*.local' \
              --exclude='*__tests__*' \
              --exclude='coverage/' \
              -e ssh \
              ./ ${EC2_USER}@${EC2_HOST}:~/timeflow/
      - run:
          name: Deploy
          command: |
            ssh $EC2_USER@$EC2_HOST "\
              set -e; \
              cd ~/timeflow; \
              docker-compose down; \
              docker system prune -af; \
              yarn install; \
              docker-compose up -d --build; \
            "

workflows:
  build_test_deploy:
    jobs:
      - lint_client # No filters means it runs on all branches and PRs
      - lint_api # No filters means it runs on all branches and PRs
      - build_and_test_client:
          requires:
            - lint_client
      - build_and_test_api:
          requires:
            - lint_api
      - deploy:
          requires:
            - build_and_test_client
            - build_and_test_api
          filters:
            branches:
              only:
                - main
